<?xml version="1.0"?>
<robot name="deflector_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass1" value="100.0" />
  <xacro:property name="mass2" value="10.0" />
  <xacro:property name="mass3" value="1.0" />
  <xacro:property name="axel_offset" value="0.1" />
  <xacro:property name="width" value="0.1" />
  <xacro:property name="lenght_a" value="2.0" />
  <xacro:property name="lenght_b" value="1.0" />
  <xacro:property name="lenght_c" value="1.0" />

  <!-- Gazebo materials -->
  <xacro:include filename="$(find deflector_robot)/urdf/deflector.gazebo" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

   <!-- To-Do: use a fixed joint to the 'world' -->
   <joint name="prismatic_joint1" type="prismatic">
     <limit effort="1000.0" lower="0" upper="1.0" velocity="0.5"/>
     <origin xyz="0 0 0  " rpy="0 0 0"/>
     <parent link="world"/>
     <child link="link1"/>
     <axis xyz="0 0 1"/>  <!-- In which axis the movement is performed -->
     <dynamics damping="0.7"/>
   </joint>


  <!-- Ground/Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	   <box size="${lenght_a} ${width} ${width} "/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
       <box size="${lenght_a} ${width} ${width} "/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass1}"/>
      <inertia
	  ixx="${mass1 / 12.0 * (width*width + lenght_a*lenght_a)}" ixy="0.0" ixz="0.0"
	  iyy="${mass1 / 12.0 * (lenght_a*lenght_a + width*width)}" iyz="0.0"
	  izz="${mass1 / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="prismatic_joint2" type="prismatic">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="${-axel_offset + width*3/2} 0 ${width}" rpy="0 0 0"/>
    <!-- specify upper and lower range of motion -->
    <!-- maximum control effort (1000 N force) and maximum velocity (1.0 m/sec) -->
    <limit effort="1000.0" lower="0" upper="${lenght_a-width}" velocity="1.0"/>
    <axis xyz="1 0 0"/>  <!-- In which axis the movement is performed -->
    <dynamics damping="10.0"/>
  </joint>

  <!-- Vertical Pole / Middle Link -->
  <link name="link2">
    <collision>
      <origin xyz="${-lenght_b} 0 ${lenght_b/2-width/2}" rpy="0 0 0"/>
      <geometry>
	   <box size="${width} ${width} ${lenght_b}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-lenght_b} 0 ${lenght_b/2-width/2}" rpy="0 0 0"/>
      <geometry>
	   <box size="${width} ${width} ${lenght_b}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 ${lenght_b/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass2}"/>
      <inertia
	  ixx="${mass2 / 12.0 * (width*width + lenght_b*lenght_b)}" ixy="0.0" ixz="0.0"
	  iyy="${mass2 / 12.0 * (lenght_b*lenght_b + width*width)}" iyz="0.0"
	  izz="${mass2 / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="prismatic_joint3" type="prismatic">
    <limit effort="1000.0" lower="0" upper="${lenght_c-width}" velocity="0.5"/>
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 ${width/2} ${lenght_b - axel_offset*2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>  <!-- In which axis the movement is performed -->
    <dynamics damping="1.0"/>
  </joint>

  <!-- Top Link -->
  <link name="link3">
    <collision>
    <origin xyz="${-lenght_b + axel_offset-width} ${-lenght_c/2-axel_offset+width} ${width*2}"
              rpy="${pi/2} 0 0"/>
      <geometry>
	   <box size="${width} ${width} ${lenght_c}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${-lenght_b + axel_offset-width} ${-lenght_c/2-axel_offset+width} ${width*2}"
              rpy="${pi/2} 0 0"/>
      <geometry>
	   <box size="${width} ${width} ${lenght_c}"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 ${lenght_c/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass3}"/>
      <inertia
	  ixx="${mass3 / 12.0 * (width*width + lenght_c*lenght_c)}" ixy="0.0" ixz="0.0"
	  iyy="${mass3 / 12.0 * (lenght_c*lenght_c + width*width)}" iyz="0.0"
	  izz="${mass3 / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <!-- declare transmissions and actuators required to interface with ROS control -->
  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="prismatic_joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="prismatic_joint3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
