<?xml version="1.0"?>
<robot name="deflector_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Set the size of robot axes, as well as their positions and orientations -->
<xacro:include filename="$(find deflector_robot)/urdf/properties.xacro" />
<!-- Gazebo materials -->
<xacro:include filename="$(find deflector_robot)/urdf/deflector.gazebo" />
<!-- Inertia Matrix Calculations -->
<xacro:include filename="$(find deflector_robot)/urdf/inertia_tensors.urdf.xacro" />

<!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="robot_to_world" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>

 <!-- Base Link -->
  <link name="link1">
    <collision>
      <xacro:insert_block name="base_link_origin" />
      <geometry>
	   <box size="${x_width_l1} ${y_width_l1} ${lenght_l1}"/>
      </geometry>
    </collision>
    <visual>
      <xacro:insert_block name="base_link_origin" />
      <geometry>
        <box size="${x_width_l1} ${y_width_l1} ${lenght_l1}"/>
      </geometry>
    </visual>
    <inertial>
      <!-- The center of each inertia box is aligned with the center of mass of its link -->
      <xacro:insert_block name="base_link_origin" />
      <mass value="${mass_l1}"/>
      <xacro:inertial_cuboid mass="${mass_l1}" x_width="${x_width_l1}" y_width="${y_width_l1}" length="${lenght_l1}" >
      </xacro:inertial_cuboid> 
    </inertial>
  </link>

<joint name="prismatic_joint1" type="prismatic">
    <parent link="link1"/>
    <child link="link2"/>
    <!-- link origin with respect to the origin of the body of the parent link -->
    <origin xyz="${-lenght_l1/2+x_width_l2/2} 0.0 ${x_width_l1}" rpy="0 0 0"/> <!-- at the beginning, on the surface -->
    <!-- specify upper and lower range of motion -->
    <!-- maximum control effort (1000 N force) and maximum velocity (1.0 m/sec) -->
    <limit effort="1000.0" lower="0" upper="${lenght_l1-x_width_l2}" velocity="1.0"/> <!-- upper 3.8 -->
    <axis xyz="1 0 0"/>  <!-- In which axis the movement is performed -->
    <dynamics damping="10.0"/>
  </joint>

  <!-- Vertical Pole / Middle Link -->
  <link name="link2">
    <collision>
      <xacro:insert_block name="middle_link_origin" />
      <geometry>
       <box size="${x_width_l2} ${y_width_l2} ${lenght_l2}"/>
      </geometry>
    </collision>

    <visual>
      <xacro:insert_block name="middle_link_origin" />
      <geometry>
	   <box size="${x_width_l2} ${y_width_l2} ${lenght_l2}"/>
      </geometry>
    </visual>
    <inertial>
      <xacro:insert_block name="middle_link_origin" />
      <mass value="${mass_l2}"/>
      <xacro:inertial_cuboid mass="${mass_l2}" x_width="${x_width_l2}" y_width="${y_width_l2}" length="${lenght_l1}" >
      </xacro:inertial_cuboid>
    </inertial>
  </link>


<joint name="prismatic_joint2" type="prismatic">
    <parent link="link2"/>
    <child link="link3"/>
    <!-- origin pose in the frame of reference of the parent link -->
    <!-- use p or y to set orientation of Gantry -->
    <origin xyz="${x_width_l2/2} 0.0 ${x_width_gantry/2}" rpy="0 ${pi/2} 0"/>
    <!-- specify upper and lower range of motion -->
    <!-- maximum control effort (1000 N force) and maximum velocity (1.0 m/sec) -->
    <limit effort="1000.0" lower="${-lenght_l2+x_width_gantry}" upper="0" velocity="1.0"/><!--low: -0.6-->
    <axis xyz="1 0 0"/>  <!-- In which axis the movement is performed -->
    <dynamics damping="10.0"/>
  </joint>

  <!-- Gantry -->
  <link name="link3">
    <collision>
      <xacro:insert_block name="gantry_link_origin" />
      <geometry>
	   <box size="${x_width_gantry} ${y_width_gantry} ${height_gantry}"/>
      </geometry>
    </collision>

    <visual>
      <xacro:insert_block name="gantry_link_origin" />
      <geometry>
	   <box size="${x_width_gantry} ${y_width_gantry} ${height_gantry}"/>
      </geometry>
    </visual>
    <inertial>
      <xacro:insert_block name="gantry_link_origin" />
            <mass value="${mass_gantry}"/>
      <xacro:inertial_cuboid mass="${mass_gantry}" x_width="${x_width_gantry}" y_width="${y_width_gantry}" length="${height_gantry}" >
      </xacro:inertial_cuboid> 
    </inertial>
  </link>

<joint name="prismatic_joint3" type="prismatic">
    <limit effort="1000.0" lower="0" upper="${lenght_l4-y_width_gantry}" velocity="0.5"/> <!-- upper:0.8 -->
    <parent link="link3"/>
    <child link="link4"/>
    <!-- origin pose in the frame of reference of the parent link -->
    <origin xyz="0 0 ${height_gantry}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>  <!-- In which axis the movement is performed -->
    <dynamics damping="1.0"/>
  </joint>

  <!-- Top Link -->
  <link name="link4">
    <collision>
    <xacro:insert_block name="top_link_origin" />
      <geometry>
	   <box size="${x_width_l4} ${y_width_l4} ${lenght_l4}"/>
      </geometry>
    </collision>

    <visual>
      <xacro:insert_block name="top_link_origin" />
      <geometry>
	   <box size="${x_width_l4} ${y_width_l4} ${lenght_l4}"/>
      </geometry>
    </visual>

    <inertial>
      <xacro:insert_block name="top_link_origin" />
      <mass value="${mass_l4}"/>
      <xacro:inertial_cuboid mass="${mass_l4}" x_width="${x_width_l4}" y_width="${y_width_l4}" length="${lenght_l4}" >
      </xacro:inertial_cuboid> 
    </inertial>
  </link>

<!-- declare transmissions and actuators required to interface with ROS control -->
<!-- defines ressource of hardware_interface::EffortJointInterface -->
  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="prismatic_joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="prismatic_joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="prismatic_joint3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

<?ignore
?> <!-- end of non-existing processing instruction -->

</robot>
